# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_cbrf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=4, max_digits=9, verbose_name='value')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_cbrf.Currency')),
            ],
            options={
                'verbose_name': 'record',
                'verbose_name_plural': 'records',
                'abstract': False,
            },
        ),
    ]
